# Epsilon lexicase

## Overview

```{r}
# Relative location of data.
working_directory <- "Hpcc/aml-reruns/2021-05-28-epsilon/analysis/"
# working_directory <- "./"                                              # << For local analysis

# Settings for visualization
cb_palette <- "Set2"
# Create directory to dump plots
dir.create(paste0(working_directory, "imgs"), showWarnings=FALSE)
```

## Analysis dependencies

```{r, message=FALSE}
library(ggplot2)
library(tidyverse)
library(cowplot)
library(viridis)
library(RColorBrewer)
source("https://gist.githubusercontent.com/benmarwick/2a1bb0133ff568cbe28d/raw/fb53bd97121f7f9ce947837ef1a4c65a73bffb3f/geom_flat_violin.R")
```

These analyses were conducted in the following computing environment:

```{r}
print(version)
```


## Setup

```{r}
data_loc <- paste0(working_directory, "data/timeseries-res-1000g.csv")
data <- read.csv(data_loc, na.strings="NONE")

data$cardinality <- as.factor(
  data$OBJECTIVE_CNT
)
data$selection_name <- as.factor(
  data$selection_name
)

data$epsilon <- as.factor(
  data$LEX_EPS
)

data$elite_trait_avg <- data$ele_agg_per / data$OBJECTIVE_CNT
data$unique_start_positions_coverage <- data$uni_str_pos / data$OBJECTIVE_CNT

final_data <- filter(data, evaluations==max(data$evaluations))

####### misc #######
# Configure our default graphing theme
theme_set(theme_cowplot())
```

## Performance

### Performance over time

Raw aggregate performances.

```{r}
ggplot(data, aes(x=gen, y=ele_agg_per, color=epsilon)) +
  stat_summary(geom="line", fun=mean) +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  scale_y_continuous(
    name="Elite aggregate performance",
    limits=c(0, 10000)
  ) +
  scale_x_continuous(
    name="Generation"
  ) +
  ggsave(
    paste(working_directory, "imgs/elite_agg_performance_ot.pdf", sep=""),
    width=10,
    height=7
  )
```

```{r}
elite_ave_performance_fig <-
  ggplot(
    data,
    aes(x=gen, y=elite_trait_avg, color=epsilon, fill=epsilon)
  ) +
  stat_summary(geom="line", fun=mean) +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  scale_y_continuous(
    name="Average trait performance"
  ) +
  scale_x_continuous(
    name="Generations"
  ) +
  scale_fill_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  scale_color_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  ggsave(
    paste(working_directory, "imgs/elite_trait_average_ot.pdf", sep="")
  )
elite_ave_performance_fig
```

### Final performance

```{r}
elite_final_performance_fig <- ggplot(
    final_data,
    aes(x=epsilon, y=elite_trait_avg, fill=epsilon)
  ) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8,
    scale="width"
  ) +
  geom_point(
    mapping=aes(color=epsilon),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  scale_y_continuous(
    name="Average trait performance",
    limits=c(0, 100)
  ) +
  scale_x_discrete(
    name="Epsilon"
  ) +
  scale_fill_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  scale_color_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  theme(
    legend.position="none"
  )
elite_final_performance_fig
```

## Unique starting positions

### Coverage over time

```{r}
ggplot(data, aes(x=gen, y=uni_str_pos, color=epsilon)) +
  stat_summary(geom="line", fun=mean) +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  scale_y_continuous(
    name="Unique starting positions (population)",
  ) +
  scale_x_continuous(
    name="Generation"
  ) +
  ggsave(
    paste(working_directory, "imgs/pop_unique_starting_positions_ot.pdf", sep="")
  )
```

```{r}
unique_start_position_coverage_fig <- ggplot(
    data,
    aes(x=gen, y=unique_start_positions_coverage, color=epsilon, fill=epsilon)
  ) +
  stat_summary(geom="line", fun=mean) +
  stat_summary(
    geom="ribbon",
    fun.data="mean_cl_boot",
    fun.args=list(conf.int=0.95),
    alpha=0.2,
    linetype=0
  ) +
  scale_y_continuous(
    name="Starting position coverage",
    limits=c(0.0, 1.0)
  ) +
  scale_x_continuous(
    name="Generations"
  ) +
  scale_fill_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  scale_color_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  ggsave(
    paste(working_directory, "imgs/pop_unique_starting_position_coverage_ot.pdf", sep="")
  )
unique_start_position_coverage_fig
```

### Final coverage

```{r}
unique_start_positions_coverage_final_fig <- ggplot(
    final_data,
    aes(x=epsilon, y=unique_start_positions_coverage, fill=epsilon)
  ) +
  geom_flat_violin(
    position = position_nudge(x = .2, y = 0),
    alpha = .8,
    scale="width"
  ) +
  geom_point(
    mapping=aes(color=epsilon),
    position = position_jitter(width = .15),
    size = .5,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = .1,
    outlier.shape = NA,
    alpha = 0.5
  ) +
  scale_y_continuous(
    name="Starting position coverage",
    limits=c(0, 1.0)
  ) +
  scale_x_discrete(
    name="Epsilon"
  ) +
  scale_fill_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  scale_color_brewer(
    name="Epsilon",
    palette=cb_palette
  ) +
  theme(
    legend.position="none"
  )
unique_start_positions_coverage_final_fig
```

## Manuscript figures

```{r}
grid <- plot_grid(
  elite_ave_performance_fig +
    ggtitle("Performance over time") +
    theme(legend.position="none"),
  elite_final_performance_fig +
    ggtitle("Final performance") +
    theme(),
  unique_start_position_coverage_fig +
    ggtitle("Start position coverage over time") +
    guides(color = guide_legend(nrow = 1), fill=guide_legend(nrow = 1)) +
    theme(
      legend.position="bottom",
      legend.box="horizontal"
    ),
  unique_start_positions_coverage_final_fig +
    ggtitle("Final start position coverage") +
    theme(),
  nrow=2,
  ncol=2,
  rel_widths=c(3,2),
  labels="auto"
)

save_plot(
  paste(working_directory, "imgs/epsilon-panel.pdf", sep=""),
  grid,
  base_width=12,
  base_height=8
)

grid
```
