---
title: "Supplemental Material for An Exploration of Exploration: Measuring the ability of lexicase selection to find obscure pathways"
author: "Jose Guadalupe Hernandez, Alexander Lalejini, and Charles Ofria"
date: "`r Sys.Date()`"
output:
  bookdown::gitbook:
    includes:
      in_header: header.html
documentclass: book
bibliography: ["packages.bib", "supplemental.bib"]
biblio-style: apalike
nocite: '@*'
link-citations: yes
github-repo: jgh9094/GPTP-2021-Exploration-Of-Exploration
description: "Supplemental material"
---

# Introduction

This is the supplemental material associated with our 2021 GPTP contribution entitled, _An Exploration of Exploration: Measuring the ability of lexicase selection to find obscure pathways_.
Preprint forthcoming.

## About our supplemental material

This supplemental material is hosted on [GitHub](https://github.com) using GitHub pages.
The source code and configuration files used to generate this supplemental material can be found in [this GitHub repository](https://github.com/jgh9094/GPTP-2021-Exploration-Of-Exploration).
We compiled our data analyses and supplemental documentation into this nifty web-accessible book using [bookdown](https://bookdown.org/).

Our supplemental material includes the following:

- Data availability (Section \@ref(data-availability))
- Guide for running our software (Section \@ref(compile-and-run-experiments))
- Experiment analyses:
  - Tournament selection versus lexicase selection (Section \@ref(tournament-selection-vs-lexicase-selection))
  - Lexicase selection at a range of diagnostic cardinalities (Section \@ref(diagnostic-cardinality))
  - Increasing population size versus increasing generations (Section \@ref(increasing-population-size-versus-increasing-generations))
  - Epsilon lexicase selection (Section \@ref(epsilon-lexicase))
  - Down-sampled lexicase selection (Section \@ref(down-sampled-lexicase))
    - Down-sampled lexicase selection (increased population size) (Section \@ref(down-sampled-lexicase-with-increased-population-size))
  - Cohort lexicase selection (Section \@ref(cohort-lexicase))
    - Cohort lexicase selection (increased population size) (Section \@ref(cohort-lexicase-with-increased-population-size))
  - Novelty-lexicase selection (Section \@ref(novelty-lexicase))


## Contributing authors

- [Jose Guadalupe Hernandez](https://jgh9094.github.io/)
- [Alexander Lalejini](https://lalejini.com)
- [Charles Ofria](http://ofria.com)